config/routes.rb
Rails.application.routes.draw do
  get 'recurs/show_report'
  get 'daily_logs/show_report'
  get 'daily_logs/import_chores'
  get 'daily_logs/new_logs'
  post 'daily_logs/who_did_last'
  post 'daily_logs/they_did_last'
  post 'daily_logs/import'
  post 'daily_logs/create_logs'
  post 'transactions/update_bulk'
  
  resources :recurs  
  resources :daily_logs, :only => [:new, :update,:edit, :destroy, :index]

  resources :transactions, :only => [:update]

  resources :rules, :only => [:new, :update, :destroy, :index]  

  devise_for :users, :controllers => { registrations: 'registrations'}

  get 'dashboard/index'
  get 'dashboard/show_report'

  resources :statements
  get 'trans_uncategorized' => 'transactions#uncategorized'

   root 'dashboard#index'

end

app/models/statement.rb
class Statement < ActiveRecord::Base    
	has_many :transactions, dependent: :destroy
	def strip_merchant(merchant)
	    puts merchant
		output = merchant.strip.scan(/\d+{13}|\D+{13}/).last
		output ||= merchant
		output.strip
    end
	def pcmastercard_profile(f,user_id)
		f.each_line do |line|
				csvline = CSV.parse_line(line.gsub(/,\s+\"/,',"'))
				transaction_params={:statement_id => self.id,
						transaction_date: Date.strptime(csvline[0], "%m/%d/%Y").to_s,
						billing_amount:csvline[2].gsub(/[\)$]/,'').gsub(/[\(]/,'-'),
						merchant: csvline[3],
						merchant_zip: csvline[6],
						mcc: csvline[9],
						category: Transaction::get_category(csvline[9].to_i, user_id),
						user_id: user_id
				}
				transaction = self.transactions.create(transaction_params)
		end
	end
	def cibc_profile(f,user_id)
		uncategorized = 0
		f.each_line do |line|
			csvline = CSV.parse_line(line.gsub(/,\s+\"/,',"'))
			merchant = strip_merchant(csvline[1])
			if csvline[4].nil?
				rule = Transaction::get_rule(merchant, user_id)
				if rule.nil?
					category = "0"
					uncategorized = uncategorized + 1
					rule_id = nil
				else
					category = rule.category
					rule_id = rule.id
				end
			else
				rule = Rule.create({merchant: merchant, category: csvline[4], user_id: user_id}) unless Rule.exists?(user_id: user_id, merchant: merchant)
				category = csvline[4]
				rule_id = nil
			end	
			transaction_params={:statement_id => self.id,
					transaction_date: Date.strptime(csvline[0], "%Y-%m-%d").to_s,
					billing_amount:"#{csvline[2].nil? ? csvline[3] : csvline[2]}".gsub(/[\)$]/,'').gsub(/[\(]/,'-'),
					merchant: csvline[1],
					merchant_zip: 0,
					mcc: 0,
					category: category,
					user_id: user_id,
					rules_id: rule_id
			}	
			transaction = self.transactions.create(transaction_params)
		end
		uncategorized
	end
	
	def manual_profile(f,user_id)
		f.each_line do |line|
		csvline = CSV.parse_line(line.gsub(/,\s+\"/,',"'))
		transaction_params={:statement_id => self.id,
				transaction_date: Date.strptime(csvline[0], "%m/%d/%Y").to_s,
				billing_amount:csvline[1].gsub(/[\)$]/,'').gsub(/[\(]/,'-'),
				merchant: csvline[2],
				merchant_zip: csvline[3],
				mcc: csvline[4],
				category: csvline[5],
				user_id: user_id
		}
		transaction = self.transactions.create(transaction_params)
		end
	end
	
	
	def import(file, user_id)
		f = file.open
		uncategorized = 0
		headers = CSV.parse_line(f.readline)
		puts headers, headers.length, headers.include?(" SICMCC Code")
		if headers.include?(" SICMCC Code") and headers.length == 10
			#PC Mastercard Profile detected
			pcmastercard_profile(f, user_id)
		elsif headers.include?("Debit") and headers.length == 5
			uncategorized = cibc_profile(f,user_id)
		elsif headers.include?("billing_amount") and headers.length == 6
			manual_profile(f,user_id)
		end
		f.close
		uncategorized
	end	
		
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :set_statement, only: [:show, :edit, :update, :destroy]

  # GET /statements
  # GET /statements.json
  def index
    @statements = current_user.dashboard.statements.all
  end
    
  # GET /statements/1
  # GET /statements/1.json
  def show
  end

  # GET /statements/new
  def new
    @statement = current_user.dashboard.statements.new
  end

  # GET /statements/1/edit
  def edit
  end

  # POST /statements
  # POST /statements.json
  def create
    @statement = current_user.dashboard.statements.new(statement_params)
	@statement.save
	id=@statement.id
	begin
		uncategorized = @statement.import(params[:file], current_user.id)
	rescue Exception => e
		@statement.destroy
		raise e
	end
    respond_to do |format|
      if @statement
		if uncategorized == 0
			format.html { redirect_to statements_url, notice: 'Statement was successfully created.' }
			format.json { render :show, status: :created, location: @statement }
		else
			format.html { redirect_to "/trans_uncategorized", alert: 'Some transactions are not categorized' }
			format.json { render :show, status: :created, location: @statement }
		end
      else
        format.html { render :new }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statements/1
  # PATCH/PUT /statements/1.json
  def update
    respond_to do |format|
      if @statement.update(statement_params)
        format.html { redirect_to statements_url, notice: 'Statement was successfully updated.' }
        format.json { render :show, status: :ok, location: @statement }
      else
        format.html { render :edit }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statements/1
  # DELETE /statements/1.json
  def destroy
    @statement.destroy
    respond_to do |format|
      format.html { redirect_to statements_url, notice: 'Statement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statement
      @statement = current_user.dashboard.statements.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statement_params
      params.require(:statement).permit(:name)
    end
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/statements/_form.html.erb
<div class="container">
	<%= form_for @statement, :html => { :multipart => true, class: 'form-horizontal', id: "new-statement-form"} do |f| %>	
		<% if @statement.errors.any? %>
			<div id="error_explanation">
			  <h2><%= pluralize(@statement.errors.count, "error") %> prohibited this statement from being saved:</h2>
			  <ul>
				  <% @statement.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				  <% end %>
			  </ul>
			</div>
		<% end %>		
		<div class="form-group">
			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				<input type="text" name="statement[name]" id="statement_name" tabindex="1" class="form-control" placeholder="Statement Name" value="">
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				<%= file_field_tag 'file', accept: '.csv', class: "form-control btn btn-default" %>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
					<input type="submit" name="commit" id="statement_submit" tabindex="4" class="form-control btn btn-primary" value="Submit Statement">
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/statements/_form_edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="container">
    	<div class="row">
			<div class="col-md-6" >		
				<%= form_for @statement, :html => { :multipart => true, class: 'form-horizontal', id: "new-statement-form"} do |f| %>	
					<% if @statement.errors.any? %>
					<div id="error_explanation">
					  <h2><%= pluralize(@statement.errors.count, "error") %> prohibited this statement from being saved:</h2>
					  <ul>
					  <% @statement.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					  <% end %>
					  </ul>
					</div>
					<% end %>				
					<div class="form-group">
						<input type="text" name="statement[name]" id="statement_name" tabindex="1" class="form-control" placeholder= "<%=@statement.name%>" value="<%=@statement.name%>">
					</div>
					<br>
					<div class="form-group">
						<div class="row">
							<div class="col-sm-6 col-sm-offset-3">
								<input type="submit" name="commit" id="statement_submit" tabindex="4" class="form-control btn btn-primary" value="Submit Statement">
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/statements/edit.html.erb
<h2>Edit Statement Name</h2>

<%= render 'form_edit' %>

app/views/statements/index.html.erb
<h2>Listing Statements</h2>

<table class="table">
  <thead>
    <tr class="row">
      <th class="col-sm-8" text-align="right">Name</th>
	  <th class="col-sm-2" text-align="center"></th>
	  <th class="col-sm-2" text-align="center"></th>
    </tr>
  </thead>

  <tbody>
    <% @statements.each do |statement| %>
      <tr class="row">
		<td class="col-sm-8"><%= statement.name %></td>
		<td class="col-sm-2"><%= link_to 'Edit Name', edit_statement_path(statement), class: "form-control btn btn-primary" %></td>
		<td class="col-sm-2"><%= link_to 'Destroy', statement, method: :delete, data: { confirm: 'Are you sure?'}, class: "form-control btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statements/new.html.erb
<h3>New Statement</h3>
<br>
<%= render 'form' %>

app/views/statements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @statement.name %>
</p>

<%= link_to 'Edit', edit_statement_path(@statement) %> |
<%= link_to 'Back', statements_path %>