config/routes.rb
Rails.application.routes.draw do
  get 'recurs/show_report'
  get 'daily_logs/show_report'
  get 'daily_logs/import_chores'
  get 'daily_logs/new_logs'
  post 'daily_logs/who_did_last'
  post 'daily_logs/they_did_last'
  post 'daily_logs/import'
  post 'daily_logs/create_logs'
  post 'transactions/update_bulk'
  
  resources :recurs  
  resources :daily_logs, :only => [:new, :update,:edit, :destroy, :index]

  resources :transactions, :only => [:update]

  resources :rules, :only => [:new, :update, :destroy, :index]  

  devise_for :users, :controllers => { registrations: 'registrations'}

  get 'dashboard/index'
  get 'dashboard/show_report'

  resources :statements
  get 'trans_uncategorized' => 'transactions#uncategorized'

   root 'dashboard#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @transactions = current_user.transactions.all
    respond_with(@transactions)
  end
  
  def uncategorized
    @transactions = current_user.transactions.where(category: "0")
	@categories = (current_user.transactions.pluck(:category).uniq - ["0"]) 
	if @categories.empty?
		@categories = ["Car expenses", "Shopping", "Eat-out", "Entertainment", "Utilities", "Groceries", "Insurance", "Mortgage", "Income", "Savings", "Payment", "Misc"]
	end
	if @transactions.length == 0
		redirect_to statements_path
	else
		respond_with(@transactions)
	end
  end
  

  def show
    respond_with(@transaction)
  end

  def new
    @transaction = Transaction.new
    respond_with(@transaction)
  end

  def edit
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.save
    respond_with(@transaction)
  end
  
  def evaluate_other_transactions
    
	uncategorized = current_user.transactions.where(category: "0")
	uncategorized.each do |transaction|
		category = Transaction::get_category(strip_merchant(transaction.merchant), current_user.id)
		if category != "0" 
			transaction.category = category
			transaction.save
		end
	end
  end

  def update
	if category != "" then
		merchant = strip_merchant(@transaction.merchant).strip
		rule = Rule.where(user_id: current_user.id, merchant: merchant).first
		rule ||= Rule.create({merchant: merchant, category: category, user_id: current_user.id})
		transaction_params[:rules_id]=rule.id
		@transaction.update(transaction_params)
		evaluate_other_transactions
	end
	redirect_to trans_uncategorized_path
  end
  
  def update_bulk
	transactions = params[:transaction] || {}
	transactions.each_pair do |id, category|
		if category != "" then
			transaction = current_user.transactions.where(id: id.to_i).first
			merchant = strip_merchant(transaction.merchant).strip
			rule = Rule.where(user_id: current_user.id, merchant: merchant).first
			rule ||= Rule.create({merchant: merchant, category: category, user_id: current_user.id})
			transaction.update(category: category, rules_id: rule.id)
		end
	end
	evaluate_other_transactions
	redirect_to trans_uncategorized_path
  end
  
  def destroy
    @transaction.destroy
    respond_with(@transaction)
  end

  private
    def set_transaction
      @transaction = current_user.transactions.find(params[:id])
    end

    def transaction_params
      params[:transaction].permit(:category)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/uncategorized.html.erb
<script>

function cleanParams() {
    var form = document.forms["update_transactions"];
	comments = $(':input[type="text"]')
	for (var i=0; i<comments.length; i++){
		if (comments[i].value == ""){
			comments[i].disabled = true;
		}
	}
	form.submit();
}
</script>
<h3>Listing uncategorized transactions</h3>
<%= form_tag("/transactions/update_bulk", {:id=>"update_transactions", :onsubmit=> "cleanParams()"}) do %>  
	<table class="table">
		<thead>
		<tr>
		  <th text-align="center">Merchant</th>
		  <th text-align="center">Category</th>
		  <th text-align="center"></th>
		  <th text-align="center"></th>
		</tr>
		</thead>
		<tbody>
			<div class="field" style="padding-top: 10px">
				<% @transactions.each do |transaction| %>
				  <tr>	  
					  <% if transaction.errors.any? %>
						<div id="error_explanation">
						  <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

						  <ul>
						  <% transaction.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						  <% end %>
						  </ul>
						</div>
					  <% end %>
					  <td><%= strip_merchant(transaction.merchant) %></td>
					  <td>
						<%= text_field_tag "transaction[#{transaction.id}]",nil, {class: "form-control", list: "categorylist"} %>	
						<datalist id='categorylist'>
							<% @categories.each do |category| %>
								<%= content_tag(:option, category) %>
							<% end %>
						</datalist>
					  </td>
					  <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' }, class:"form-control btn btn-warning"  %></td>
				  </tr>
				<% end %>
			</div>
		</tbody>
	</table>
	<div class="row">
		<div class="form-group col-md-4"></div>
		<div class="form-group col-md-4">
			<input type="submit" name="commit" id="transaction_submit" class="form-control btn btn-primary" value="Update">
		</div>
		<div class="form-group col-md-4"></div>
	</div>
<% end %>		
<br>
