config/routes.rb
Rails.application.routes.draw do
  get 'recurs/show_report'
  get 'daily_logs/show_report'
  get 'daily_logs/import_chores'
  get 'daily_logs/new_logs'
  post 'daily_logs/who_did_last'
  post 'daily_logs/they_did_last'
  post 'daily_logs/import'
  post 'daily_logs/create_logs'
  post 'transactions/update_bulk'
  
  resources :recurs  
  resources :daily_logs, :only => [:new, :update,:edit, :destroy, :index]

  resources :transactions, :only => [:update]

  resources :rules, :only => [:new, :update, :destroy, :index]  

  devise_for :users, :controllers => { registrations: 'registrations'}

  get 'dashboard/index'
  get 'dashboard/show_report'

  resources :statements
  get 'trans_uncategorized' => 'transactions#uncategorized'

   root 'dashboard#index'

end

app/models/rule.rb
class Rule < ActiveRecord::Base
	belongs_to :user
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @rules = current_user.rules.all
    respond_with(@rules)
  end
    
  def show
    respond_with(@rule)
  end

  def new
    @rule = current_user.rules.new
    respond_with(@rule)
  end

  def edit
  end

  def create
    @rule = current_user.rules.new(rule_params)
    @rule.save
    respond_with(@rule)
  end

  def reevaluate_transactions(rule)
	transactions = current_user.transactions.where(rules_id: rule.id)
	transactions.each do |transaction|
		if transaction.category != rule.category
			transaction.category = rule.category
			transaction.save
		end
	end
  end
  def update
    @rule.update(rule_params)
	reevaluate_transactions(@rule)
	redirect_to rules_path
  end

  def destroy
    @rule.destroy
    respond_with(@rule)
  end

  private
    def set_rule
      @rule = current_user.rules.find(params[:id])
    end

    def rule_params
      params.require(:rule).permit(:merchant, :category)
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :merchant %><br>
    <%= f.text_field :merchant %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<h2>Listing Rules</h2>

<table class="table">
  <thead>
    <tr>
      <th text-align="center">Merchant</th>
      <th text-align="center">Category</th>
	  <th text-align="center"></th>
	  <th text-align="center"></th>
    </tr>
  </thead>

  <tbody>
	<% @rules.each do |rule| %>
		<tr>
			<%= form_for(rule) do |f| %>
				<% if rule.errors.any? %>
					<div id="error_explanation">
						<h2><%= pluralize(rule.errors.count, "error") %> prohibited this rule from being saved:</h2>
						<ul>
							<% rule.errors.full_messages.each do |message| %>
								<li><%= message %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
				<td><div class="form-group" style="padding-top: 10px"><%= rule.merchant %></div></td>
				<td>
				<div class="form-group">
					<%= f.text_field :category, {class: "form-control"} %>
				</div>								
				</td>
				<td>
				<div class="actions">
					<%= f.submit "Update", {class:"form-control btn btn-primary"}  %>
				</div>
				</td>
				<td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' }, class:"form-control btn btn-warning"  %></td>
			<% end %>	  
		</tr>
	<% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Merchant:</strong>
  <%= @rule.merchant %>
</p>

<p>
  <strong>Category:</strong>
  <%= @rule.category %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>