config/routes.rb
Rails.application.routes.draw do
  get 'recurs/show_report'
  get 'daily_logs/show_report'
  get 'daily_logs/import_chores'
  get 'daily_logs/new_logs'
  post 'daily_logs/who_did_last'
  post 'daily_logs/they_did_last'
  post 'daily_logs/import'
  post 'daily_logs/create_logs'
  post 'transactions/update_bulk'
  
  resources :recurs  
  resources :daily_logs, :only => [:new, :update,:edit, :destroy, :index]

  resources :transactions, :only => [:update]

  resources :rules, :only => [:new, :update, :destroy, :index]  

  devise_for :users, :controllers => { registrations: 'registrations'}

  get 'dashboard/index'
  get 'dashboard/show_report'

  resources :statements
  get 'trans_uncategorized' => 'transactions#uncategorized'

   root 'dashboard#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spending</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--
<%# if notice %>
  <p class="alert alert-success"><%# notice %></p>
<%# end %>
-->
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
 <% if user_signed_in? %>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <%= link_to 'Dashboard', root_path, class: "navbar-brand" %>
		</div>
	<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Money Matters<span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li> <%= link_to 'Import Statement', new_statement_path %> </li>
					<li> <%= link_to 'Manage Statements', statements_path %> </li>
					<li> <%= link_to 'Statement Rules', rules_path %> </li>
					<li> <%= link_to 'Budget Planner', recurs_path %> </li>
				</ul>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Housework Matters<span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li> <%= link_to 'New Chore Log', daily_logs_new_logs_path %> </li>
					<li> <%= link_to 'Chores Log', daily_logs_path %> </li>
				</ul>
			</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="navbar-text"> Logged in as <strong><%= current_user.email %></strong>. </li>
				<li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
				<li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
			</ul>
		</div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
</nav>
<% else %>
<br>
<br>
<br>
<% end %>
<%= yield %>

</body>
</html>